CREATE DATABASE hub_filmes;

USE hub_filmes;

CREATE TABLE filmes (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    
    NOME VARCHAR(100) NOT NULL,
    GENERO VARCHAR(50) NOT NULL,
    NOTA DECIMAL(3,1) UNSIGNED NOT NULL,
    IMAGEM VARCHAR(255) DEFAULT NULL
);